### ISSUE TITLE
scripts/power.py is not Python 3 compatible

### ISSUE THREAD

**Issue by kierdavis** [srobo/kit-maintenance-docs#19]
```python
self.handle.controlWrite(0, 64, val, cmd, "\0")
```

should be

```python
self.handle.controlWrite(0, 64, val, cmd, b"\0")
```

for Python 3. However, does this break Python 2 compatibility (and do we care?)

**Comment by kierdavis** [comment]
I've decided that I don't care, hence #20.

**Comment by PeterJCLaw** [comment]
`b'x'` works in Python 2.7; we should make this change.
